"""add issues

Revision ID: d95a911c7301
Revises: f3630374e617
Create Date: 2026-09-27 03:12:41.947545

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d95a911c7301"
down_revision: Union[str, Sequence[str], None] = "f3630374e617"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issues",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="todo", nullable=False
        ),
        sa.Column(
            "priority", sa.String(length=20), server_default="medium", nullable=False
        ),
        sa.Column("reporter_id", sa.Uuid(), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'medium', 'high')", name="ck_issues_priority"
        ),
        sa.CheckConstraint(
            "status IN ('todo', 'in_progress', 'done')", name="ck_issues_status"
        ),
        sa.CheckConstraint("number > 0", name="ck_issues_number_positive"),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "number", name="uq_issues_project_number"),
    )
    op.create_index(
        op.f("ix_issues_assignee_id"), "issues", ["assignee_id"], unique=False
    )
    op.create_index(
        op.f("ix_issues_project_id"), "issues", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_issues_reporter_id"), "issues", ["reporter_id"], unique=False
    )
    op.create_index(op.f("ix_issues_status"), "issues", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_issues_status"), table_name="issues")
    op.drop_index(op.f("ix_issues_reporter_id"), table_name="issues")
    op.drop_index(op.f("ix_issues_project_id"), table_name="issues")
    op.drop_index(op.f("ix_issues_assignee_id"), table_name="issues")
    op.drop_table("issues")
    # ### end Alembic commands ###
